MvcCoreApiCrudHospitales/Models/ErrorViewModel.cs
namespace MvcCoreApiCrudHospitales.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreApiCrudHospitales/Models/Hospital.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreApiCrudHospitales.Models
{
    public class Hospital
    {
        public int IdHospital { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int NumeroCamas { get; set; }
    }
}

MvcCoreApiCrudHospitales/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreApiCrudHospitales.Models;
using System.Diagnostics;

namespace MvcCoreApiCrudHospitales.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreApiCrudHospitales/Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreApiCrudHospitales.Models;
using MvcCoreApiCrudHospitales.Service;
using System.Numerics;

namespace MvcCoreApiCrudHospitales.Controllers
{
    public class HospitalesController : Controller
    {
        private ServiceApiHospitales service;

        public HospitalesController(ServiceApiHospitales service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Hospital> hospitales =
                await this.service.GetHospitalesAsync();
            return View(hospitales);
        }
        public async Task<IActionResult> Details(int id)
        {
            Hospital hospital =
                await this.service.FindHospitalAsync(id);
            return View(hospital);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Hospital hos)
        {
            await this.service.InsertHospitalAsync
                (hos.Nombre, hos.Direccion, hos.Telefono, hos.NumeroCamas);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Hospital hospital =
                await this.service.FindHospitalAsync(id);
            return View(hospital);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Hospital hos)
        {
            await this.service.UpdateHospitalAsync
                (hos.IdHospital, hos.Nombre, hos.Direccion, hos.Telefono, hos.NumeroCamas);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.service.DeleteHospitalAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreApiCrudHospitales/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreApiCrudHospitales/Views/Hospitales/Create.cshtml
@model MvcCoreApiCrudHospitales.Models.Hospital

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hospital</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input name="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input name="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input name="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCamas" class="control-label"></label>
                <input type="number" name="NumeroCamas" class="form-control" />
                <span asp-validation-for="NumeroCamas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Hospitales">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcCoreApiCrudHospitales/Views/Hospitales/Details.cshtml
@model MvcCoreApiCrudHospitales.Models.Hospital

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hospital</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdHospital)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdHospital)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCamas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCamas)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="Hospitales">Back to List</a>
</div>

MvcCoreApiCrudHospitales/Views/Hospitales/Edit.cshtml
@model MvcCoreApiCrudHospitales.Models.Hospital

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Hospital</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdHospital" class="control-label"></label>
                <input type="hidden" name="IdHospital" class="form-control" value="@Model.IdHospital" />
                <span asp-validation-for="IdHospital" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" value="@Model.Nombre" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" value="@Model.Direccion" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" value="@Model.Telefono" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCamas" class="control-label"></label>
                <input asp-for="NumeroCamas" class="form-control" value="@Model.NumeroCamas" />
                <span asp-validation-for="NumeroCamas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Hospitales">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MvcCoreApiCrudHospitales/Views/Hospitales/Index.cshtml
@model IEnumerable<MvcCoreApiCrudHospitales.Models.Hospital>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" asp-controler="Hospitales">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdHospital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroCamas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdHospital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroCamas)
            </td>
            <td>
                <a asp-controller="Hospitales"
                    asp-action="Details"
                    asp-route-id="@item.IdHospital"
                    class="btn btn-outline-info">
                    Details
                </a>
                    <a asp-controller="Hospitales"
                    asp-action="Edit"
                    asp-route-id="@item.IdHospital"
                    class="btn btn-outline-success">
                    Update
                </a>
                    <a asp-controller="Hospitales"
                    asp-action="Delete"
                    asp-route-id="@item.IdHospital"
                    class="btn btn-outline-danger">
                    Delete
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreApiCrudHospitales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreApiCrudHospitales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreApiCrudHospitales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreApiCrudHospitales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Hospitales" asp-action="Index">Hospitales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreApiCrudHospitales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>